version: "3"

services:
  web:
    # Берем Dockerfile из каталога app
    build:
      context: .
      dockerfile: Dockerfile.prod
    # Запускаем сервер gunicorn
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    # Открываем порт 8000 наружу
    expose:
      - 8000
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    # Файл содержащий переменные для контейнера
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: on-failure
    env_file:
      - .env.prod.db
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    build: ./nginx
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  pg_data:
  static_volume:
  media_volume:
