# Generated by Django 5.1.3 on 2024-12-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="element_chain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="chain.elementchain",
                verbose_name="Звено сети",
            ),
        ),
    ]
